# Generated by Django 5.0 on 2024-03-04 15:56

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0002_rename_break_time_class_break_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('user', 'class_id')},
        ),
    ]
