# Generated by Django 5.0.3 on 2024-04-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0003_alter_class_end_time_alter_class_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='professor_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
