# Generated by Django 5.0.4 on 2024-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0005_remove_class_break_end_2_remove_class_break_start_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_strength',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='dob',
            field=models.DateField(default='2024-04-21'),
        ),
    ]
