# Generated by Django 5.0.4 on 2024-04-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0006_class_class_strength_professor_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='dob',
        ),
    ]
