# Generated by Django 5.0.3 on 2024-04-28 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0008_professor_dob_alter_class_class_strength'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='class',
            name='break_end',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='break_start',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch_name',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('MCA', 'MCA')], max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('MCA', 'MCA'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('CHE', 'CHE')], max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='semester',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='dob',
            field=models.DateField(default='2024-04-29'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('department_name', 'branch_name', 'semester')},
        ),
    ]
