# Generated by Django 5.0.3 on 2024-04-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0011_alter_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.professor'),
        ),
    ]
