# Generated by Django 5.0.3 on 2024-04-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0012_course_professer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='professer',
            new_name='professor',
        ),
    ]
